server:
  port: 3020
spring:
  datasource:
    druid:
      ########## 配置WebStatFilter，用于采集web关联监控的数据 ##########
      web-stat-filter:
        enabled: true                   # 启动 StatFilter
        url-pattern: /*                 # 过滤所有url
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" # 排除一些不必要的url
        session-stat-enable: true       # 开启session统计功能
        session-stat-max-count: 1000    # session的最大个数,默认100
      ########## 配置StatViewServlet（监控页面），用于展示Druid的统计信息 ##########
      stat-view-servlet:
        enabled: true                   # 启用StatViewServlet
        url-pattern: /druid/*           # 访问内置监控页面的路径，内置监控页面的首页是/druid/index.html
        reset-enable: false              # 不允许清空统计数据,重新计算
        login-username: root            # 配置监控页面访问密码
        login-password: 123
        allow: 127.0.0.1           # 允许访问的地址，如果allow没有配置或者为空，则允许所有访问
        deny:                                        # 拒绝访问的地址，deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝
    dynamic:
      type: com.alibaba.druid.pool.DruidDataSource #com.zaxxer.hikari.HikariDataSource #com.alibaba.druid.pool.DruidDataSource
      primary: db1
      hikari:
        maximumPoolSize: 100
        connectionTimeout: 50000
      druid:
        max-active: 56
        connectTimeout: 40000
        filters: stat,wall,slf4j
        # 自己配置监控统计拦截的filter
        filter:
          # 开启druiddatasource的状态监控
          stat:
            enabled: true
            db-type: mysql
            # 开启慢sql监控，超过2s 就认为是慢sql，记录到日志中
            log-slow-sql: true
            slow-sql-millis: 2000
          wall:
            enabled: true
          # 日志监控，使用slf4j 进行日志输出
          slf4j:
            enabled: true
            statement-log-error-enabled: true
            statement-create-after-log-enabled: false
            statement-close-after-log-enabled: false
            result-set-open-after-log-enabled: false
            result-set-close-after-log-enabled: false
      datasource:
        db1:
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: 'root'
          password: 'root'
          url: jdbc:mysql://127.0.0.1:3306/db1?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
          hikari:
            maximum-pool-size: 99
          druid:
            max-active: 45
        db2:
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: 'root'
          password: 'root'
          url: jdbc:mysql://127.0.0.1:3306/db2?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
logging:
  level:
    com.github.deeround.dynamic.datasource: debug

